name: Create documentation site
on: # update file
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Install tools
        run: dotnet tool restore
      - name: Generate Site
        run: dotnet docfx docs/docfx.json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node dependencies
        working-directory: build
        run: npm ci
      - name: Setup GIT identity
        run: |
          git config --global user.email "als_uk@yahoo.com"
          git config --global user.name "alunacjones"
      - name: Publish docs site
        working-directory: build
        run: npm run docs