name: Create documentation site
on: # update file
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Install tools
        run: dotnet tool restore
      - name: Generate Site
        run: dotnet docfx docs/docfx.json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install gh-pages
        run: npm install -g gh-pages
      - name: Deploy site
        run: gh-pages -d docs/_sites